{% set name = "flask-cors" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/corydolphin/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 229f273a5dd5ba6095ff162771d182fdc26070efa074fb83d54d4e83d0974405
  patches:
    - patches/0001-fix-hardcoded-version.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  build:
    - patch  # [not win]
    - msys2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - flask >=0.9
    - werkzeug >=0.7

test:
  source_files:
    - tests
  imports:
    - flask_cors
    - flask_cors.core
    - flask_cors.decorator
    - flask_cors.extension
    - flask_cors.version
  commands:
    - pip check
    - python -c "from importlib.metadata import version; print(version('{{ name|replace('-', '_') }}'))"
    - pytest -v tests
  requires:
    - pip
    - pytest >=7.2.0

about:
  home: https://corydolphin.github.io/flask-cors
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A Flask extension for handling Cross Origin Resource Sharing (CORS), making cross-origin AJAX possible.
  description: |
    A Flask extension for handling Cross Origin Resource Sharing (CORS), making cross-origin AJAX possible.
    This package has a simple philosophy: when you want to enable CORS, you wish to enable it for all use cases on a domain.
    This means no mucking around with different allowed headers, methods, etc.
    By default, submission of cookies across domains is disabled due to the security implications.
    Please see the documentation for how to enable credential’ed requests, and please make sure you add some sort of CSRF protection before doing so!
  doc_url: https://corydolphin.github.io/flask-cors
  dev_url: https://github.com/corydolphin/flask-cors

extra:
  recipe-maintainers:
    - pmlandwehr
  skip-lints:
    # use newer patcher for win
    - patch_must_be_in_build
