travis:
  secure:
    BINSTAR_TOKEN: XoRZtGJmk0eYzu4qb7INS7K41ObL1MpWOdRtzhAbYZRlNa7DzxaB7krVD16U9pimHP5Ndgg2t+9dvpLnUckFMLZHxAq3JJLRkOeAs0h1HpkKmSJ+z2SbKMZzN9Oei/z67Xs+nkZ4gNtLH2+NBmJ24xAqqwsSGpZVdbn7lHuB/y88yYHySLI1+Dsx8kiNIJcjgkRgTiCYGhwXc7Jx6Xg1hRARIUyOAvkHafvDow6SbhpUKmR4x+jjVa47P7zk7b8FUcJpTtC5/cZDeramYNFPmsnVNTrD70jEfQDTRf270wk6QxoWAH7htMYGU96uMSmjma8cDYWEwBChQHuyHlFcZWHMc+khofZWKv3vRAurPFgYbaWVhJJ5BCu1W0WBSDtMQdG+TbNDWhr4ibbOaxIXbPwxQ41fNzFjMn5SxSILRCNNF4jOSUKMSFROQq2AiGr4lbvLY88umGOgKUhWQfB1qLxZ0o4By4L/fzFqf96QT9kAG2/JYTFS8NeLZoI0EZJSwC9OS4Wo2+rlPUitLYCPTxljL/0VyztSLJkvGmC+tjVxRXHsrQEYPNfoRfZGwYHSVb4CDQpa58IjE0JEa7TplJAXEk7CjUjD6G4mac6zFLoK4q53L35AXdCGP4lV87efQr1NmROuILMpTpQwRxdMd+4tpjLy3+TD+vQcRvzRPAg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
