travis:
  secure:
    BINSTAR_TOKEN: RdBNPNubIZWz2Q+vhBqHkvftar7VvdShGClg24RWi1nxEnH+MY7BccpmPZrXDJi8yLC1k1K8w9LoFsp4GsFVHnNYmq1GpCutlFtYMR4I+xBq+ruUNwSl8t70GRzNh+jhq+isLhZi6dUKSb59tTClHtqmaNdIbADkqV2yFxqQNfPisH2zq9QqnRoj9wNwksHTgodly4Mr7qvdROVlqhHiw9RwRLsy0TmWEvn8jVdU5hn40pa71AyHQEMWKlZWLRPs0rS4HOqEcWi/IEXCFiSdOSN2cywt6HqZ/Py4DQCDh6O2H4Pa/FvK4TO6LyNrkFs16hbh6MaMdYQWEOEfz/qqwF7vO44SnjUNDOJCG7T5xHr74NP+m+aaPIF5HYnt232n69OYgaUCiPc1G1jSCT2araS/R7x+SG4atwPD1CIRMHBVxIgMw9IvirXeIO0CGZXNRZCXJV81tNgoZfVkjzQx7USMsdQjfKOo5Qlb7/62Z/zeBoq/yTtipv3iLu3m12zVdRhzb0bZ5Nq9fkTUzRjhFlxL9TBuOK3n3sDuGwUYAt3XAj1Ic1rYpUgxw8jCztvcVPoFm+csy3LOU3wrkUkYRIYTSjwgreXwHbchHXvDmegdMw4ywBS325/z2dtoM4eWngUU+w47hnikPrn7WDjW499aGkEOVY8PE4oiNn6zK/A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
