travis:
  secure:
    BINSTAR_TOKEN: U3D119P9ybKN1WdLWZ8RPJSKNQrJxwIRD7qHI6SI8Hn0JG/8je128SvIguSWzhUz7hLX2mXBnDD07MBVHDka7fcHw5X0Xeap6DGrdkj6c3MSPIXXgMkK9oor/R0caum7BZ3wI2EK5e1yse/v3boUSXt39YEDEiOKbS3/eCq2eBzDgz1ooZGcSKEbEQi+gKuzTESCobnf7pv8WuDGplegUiQnIfpO93SKtDdcGwwsVTypEPY2yuInkDDU2N2TjYHAc+wQ1EJFLi+gZsOsOH61iSfBldxo5CoRrsp9YdSg1DLZf41Dq9O6u93hM5KjlNSNT3owFT7MzdyU1Se8g29QJMerpKXVeqmL88EQHsWPWMs4i4InCubyMBOyS34AaGFgH11MJnqu+b+NjNVWTI8KIxoDVmkxhwxLMOcQ7SkUg7uD7CTOICQEOh/yMphRYCd0+hJRo0g6bUm0PDp4RXK6ucWSaY3X0wJo7GVD6yI6I/p3yP0cC1E8nsSYSdzCiSKJ1tG7wQMnjGqxk4DEmkSqIU3R5wLMWhFiT6tm8Sa77UJlpa0p+h2DanKNVafFFFrTOnCfI1l6rZWQmn5Wn2nQtC+VtRwYY1kwOfXd/Zb+Pt2zPNespUcol5646JtmDfhHcsTDShoweWcukeN7qEnHNe5macqLCz3nwuK2WDyutRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
